# Profistant AI Secrets Configuration
# Replace 'your_gemini_api_key_here' with your actual Gemini API key
# Get your API key from: https://makersuite.google.com/app/apikey

GEMINI_API_KEY = "AIzaSyCjItGvwF08DnhS6iccmbwOTc530znx9T8"
